### ISSUE TITLE
Выход из hibernate

### ISSUE THREAD

**Issue by mikken** [dmage/co2mon#10]
После выхода из hibernate получаю многократно повторяющееся сообщение в лог от ядра, пока не переткну девайс:

usb 4-1.4: usbfs: process 326 (monitor_loop) did not claim interface 0 before use

Пре пететыке у меня co2mond перезапускается автоматически — через правила udev и systemd-сервис.

**Comment by dmage** [comment]
Подвержена ли данной проблеме версия из бранча hidapi? У меня, к сожалению, сейчас нет возможности проверить под Linux.

**Comment by mikken** [comment]
Из hidapi всё нормально, но оттуда сразу не скоипилировалось, пришлось добавить #include <stdint.h> в co2mon-dumper/src/main.c

Были 2 ошибки:
main.c:29:20: error: unknown type name ‘uint16_t’

**Comment by dmage** [comment]
Спасибо, добавил.

**Comment by dmage** [comment]
В master'е теперь версия основанная на hidapi.
