### ISSUE TITLE
Почему в README нет ссылки на co2meter.com?

### ISSUE THREAD

**Issue by maklaut** [dmage/co2mon#12]
Вот это похоже оригинальный девайс - http://www.co2meter.com/collections/fixed-wall-mount/products/co2mini-co2-indoor-air-quality-monitor
Внизу страницы есть ссылка на описание USB протокола - http://www.co2meters.com/Documentation/AppNotes/AN135-CO2mini-usb-protocol.pdf

**Comment by dmage** [comment]
Действительно похоже, но нет никакой уверенности в этом. Клонов очень много. Вот сходу нашлась еще парочка:
http://www.kk-custom.co.jp/emp/CO2-mini.html
http://dostmann-electronic.de/product/id/620

"Описание" USB протокола — это слегка модифицированная страница 8 из [одной документации ZyAura][1]. Если внимательно посмотреть, то вся эта информация также содержится в ZyAura ZG01C Module Manual, на который есть ссылка в README. И, если быть честным, к USB протоколу не имеет практически никакого отношения. Этого описания недостаточно чтобы написать приложение.

[1]: https://revspace.nl/images/archive/2/2e/20140326204134!ZyAura_CO2_Monitor_Carbon_Dioxide_ZG01_Module_english_manual-1.pdf

**Comment by maklaut** [comment]
Спасибо за ответ!
