### ISSUE TITLE
Возможность: прочитать текущие значения и выйти

### ISSUE THREAD

**Issue by Speakus** [dmage/co2mon#15]
Было бы полезно сигналить себе из crontab.
команда `./co2mond/co2mond | grep CntR | head -n 1` у меня почему-то не сработала...

**Comment by Speakus** [comment]
хм... интересно что команда `./co2mond/co2mond | grep CntR | cat` тоже не срабатывает, хотя `./co2mond/co2mond | grep CntR` нормально срабатывает...

**Comment by dmage** [comment]
Из документации по grep:
```
By default, output is line buffered when standard output is a terminal and block buffered otherwise.
```
Так что желаемого поведения можно добиться такой командой:
```
./co2mond/co2mond | grep --line-buffered CntR | head -n 1
```

**Comment by Speakus** [comment]
О, спасибо! Только, конечно, такая команда подвисает пока не получит следующее значение CntR - но всё равно лучше чем ничего.

**Comment by dmage** [comment]
Устройство не позволяет запросить данные, можно только слушать новые значения. Если хочется мгновенно получать текущие значения, то можно запустить co2mond как демона и текущие значения читать из файлов.

**Comment by Speakus** [comment]
Спасибо за разъяснения.
