### ISSUE TITLE
Build on Debian jessie

### ISSUE THREAD

**Issue by Chudsaviet** [dmage/co2mon#30]
[CMakeError.txt](https://github.com/dmage/co2mon/files/588844/CMakeError.txt)
[CMakeOutput.txt](https://github.com/dmage/co2mon/files/588845/CMakeOutput.txt)

Please, help me build co2mon on Debian jessie.
I'm having next error during cmake run:

> chudsaviet@co2mon:~/co2mon/build$ cmake ..
> -- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
> -- checking for one of the modules 'hidapi-libusb;hidapi'
> CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:425 (message):
>   None of the required 'hidapi-libusb;hidapi' found
> Call Stack (most recent call first):
>   libco2mon/CMakeLists.txt:7 (pkg_search_module)
> 
> 
> -- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
> -- checking for one of the modules 'hidapi-libusb;hidapi'
> CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:425 (message):
>   None of the required 'hidapi-libusb;hidapi' found
> Call Stack (most recent call first):
>   co2mond/CMakeLists.txt:5 (pkg_search_module)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/chudsaviet/co2mon/build/CMakeFiles/CMakeOutput.log".
> See also "/home/chudsaviet/co2mon/build/CMakeFiles/CMakeError.log".
> 

CmakeOutput and CMakeError are attached.

Packages libusb-dev, libusb-1-0-0-dev and libhidapi-dev are installed.
CMake is 3.0.7, also tried 3.7 from sid.

**Comment by Vascom** [comment]
Do you have pkgconfig installed?

**Comment by Self-Perfection** [comment]
@Chudsaviet 
Probably you need package `libhidapi-libusb0` too

**Comment by Chudsaviet** [comment]
Many thanks.
`libhidapi-libusb0` is already installed
Installing `pkgconfig` helped :)
