### ISSUE TITLE
cmake mac os  None of the required 'hidapi-libusb;hidapi' found

### ISSUE THREAD

**Issue by atrbx5** [dmage/co2mon#31]
Почитал закрытый таск по mac os, попробовал:
brew install libusb
brew install hidapi
осталась ошибка

$ cmake ..
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Checking for one of the modules 'hidapi-libusb;hidapi'
CMake Error at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindPkgConfig.cmake:646 (message):
  None of the required 'hidapi-libusb;hidapi' found
Call Stack (most recent call first):
  libco2mon/CMakeLists.txt:7 (pkg_search_module)

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Checking for one of the modules 'hidapi-libusb;hidapi'
CMake Error at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/FindPkgConfig.cmake:646 (message):
  None of the required 'hidapi-libusb;hidapi' found
Call Stack (most recent call first):
  co2mond/CMakeLists.txt:5 (pkg_search_module)

**Comment by dmage** [comment]
Похоже не хватает pkg-config

**Comment by Vascom** [comment]
Ага, уже не в первый раз :)

**Comment by atrbx5** [comment]
о норм, добавте что-ли в описание, тем более, что не первый раз...
`
brew install libusb
brew install hidapi
brew install pkg-config
`

**Comment by dmage** [comment]
Добавил.
