### ISSUE TITLE
Raspberry pi compilation error

### ISSUE THREAD

**Issue by hram** [dmage/co2mon#4]
Пытаюсь скомпилировать под raspbery pi но не находит библиотеки:

pi@raspberrypi ~/co2mon/build $ cmake ..
-- checking for module 'libusb-1.0'
--   package 'libusb-1.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:8 (pkg_check_modules)

-- checking for module 'glib-2.0>=2.40'
--   package 'glib-2.0>=2.40' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:9 (pkg_check_modules)

-- checking for module 'gio-2.0'
--   package 'gio-2.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:10 (pkg_check_modules)

-- Configuring incomplete, errors occurred!

Устанавливал:
sudo apt-get install libusb-dev
sudo apt-get install libusb-1.0-0 libudev0 pm-utils

**Comment by dmage** [comment]
Попробуй так:
```
sudo apt-get install cmake libusb-1.0-0-dev libglib2.0-dev
```

**Comment by hram** [comment]
Спасибо помогло. Компиляция прошла вроде как успешно. Но теперь другая ошибка

pi@raspberrypi ~/co2mon/graph $ make graph.rrd
# 17280 = 24*60*60/5
# 12 = 60/5
# 43200 = 30*24*60*60/60
rrdtool create graph.rrd --step 5 \
        \
        DS:CO2:GAUGE:60:0:3000 \
        DS:TEMP:GAUGE:60:0:40 \
        DS:x6d:GAUGE:60:0:3000 \
        DS:x56:GAUGE:60:8000:10000 \
        \
        RRA:AVERAGE:0:1:17280 \
        RRA:AVERAGE:0.5:12:43200
make: rrdtool: Command not found
Makefile:2: recipe for target 'graph.rrd' failed
make: *** [graph.rrd] Error 127

**Comment by hram** [comment]
помогла установка rrdtool
sudo apt-get install rrdtool

**Comment by hram** [comment]
следующая ошибка
pi@raspberrypi ~/co2mon/graph $ ./update_data.sh
No CO2 device found
Traceback (most recent call last):
  File "./monitor.py", line 3, in <module>
    import gobject
ImportError: No module named gobject

**Comment by hram** [comment]
установил python-gobject
sudo apt-get install python-gobject

но теперь пишет:
No CO2 device found

**Comment by hram** [comment]
Вставил датчик в USB

pi@raspberrypi ~/co2mon/graph $ ./update_data.sh
Bus 001 Device 008
libusb_open: Access denied (insufficient permissions)
Unable to contact with CO2 device

Запустил с правами администратора
pi@raspberrypi ~/co2mon/graph $ sudo ./update_data.sh
Bus 001 Device 008
Sending values to D-Bus...
TEMP 26.0375
./update_data.sh: 14: ./update_data.sh: [[: not found
./update_data.sh: 17: ./update_data.sh: [[: not found
CO2 804
./update_data.sh: 14: ./update_data.sh: [[: not found
./update_data.sh: 17: ./update_data.sh: [[: not found
TEMP 25.975
./update_data.sh: 14: ./update_data.sh: [[: not found
./update_data.sh: 17: ./update_data.sh: [[: not found
CO2 801

**Comment by dmage** [comment]
Добавил #!/bin/bash в ./update_data.sh, ошибка должна пропасть.

**Comment by hram** [comment]
Спасибо!
Вот что в итоге получилось. Это нормально?
pi@raspberrypi ~/co2mon/graph $ ./update_data.sh
Bus 001 Device 008
Unable to acquire bus name 'io.github.dmage.CO2Mon'. Check your /etc/dbus-1/system.d/
Bus 001 Device 008
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.000000] [000061db] libusbx: error [op_open] libusbx couldn't open USB device /dev/bus/usb/001/008: Permission denied.
[ 0.020048] [000061db] libusbx: error [op_open] libusbx requires write access to USB device nodes.
libusb_open: Access denied (insufficient permissions)
Unable to contact with CO2 device
TEMP 25.7875
CO2 981
TEMP 25.7875
CO2 986
TEMP 25.7875

**Comment by dmage** [comment]
В graph/ лежит пример как можно использовать данные co2mond, простые скрипты в 20 строк.
Там нет обработки ситуаций когда что-то идет не так.

Судя по выводу, в фоне уже запущен co2mond. В результате у update_data.sh не получилось запустить 2-ю копию, но т.к. в update_data.sh нет проверок на ошибки, то выполнение пошло дальше и у скрипта получилось подключиться к 1-й копии.

Я хочу в итоге это пример заменить отдельным клиентом для InfluxDB. Но сейчас код, который у меня есть для InfluxDB, опять-таки имеет проблемы в ситуации недоступности InfluxDB.

Дополнительно хочу собрать пакеты все этого для Raspbian, но в нем нет systemd/upstart и значит нужно делать свой

**Comment by Displacer** [comment]
dmage, еще интересно было бы OpenWRT, к роутеру подключать. Но там ко всему еще нет dbus.

**Comment by dmage** [comment]
@Displacer, а на OpenWRT есть Graphite/InfluxDB/какая-нибудь рисовалка графиков? С OpenWRT, к сожалению, не имел дела.
