### ISSUE TITLE
How to kill process

### ISSUE THREAD

**Issue by hram** [dmage/co2mon#6]
How to kill process that was started from command make graph.rrd ?

**Comment by dmage** [comment]
```
$ time make graph.rrd
real    0m0.042s
user    0m0.006s
sys     0m0.005s
```
If execution time of this command is much longer, then you have big problems.
However, you can press Ctrl+C to send a termination signal to the rrdtool process.

**Comment by hram** [comment]
My mistake. How can I kill infinite loop runed after command
> ./update_graph.sh >/dev/null &

**Comment by dmage** [comment]
```
$ jobs
[1]-  Running                 sleep 60 &
[2]+  Running                 ./update_graph.sh > /dev/null &
$ kill %2
[2]+  Terminated              ./update_graph.sh > /dev/null
```

**Comment by hram** [comment]
thanks a lot
