### ISSUE TITLE
Mac OS X

### ISSUE THREAD

**Issue by Anonym-tsk** [dmage/co2mon#7]
Привет. Установил из brew всё необходимое, компиляция прошла успешно. Но при запуске вижу
~/co2mon/build $ ./co2mond
Unable to connect to D-Bus: Не удалось подключиться к: No such file or directory

**Comment by dmage** [comment]
Привет. Вероятно не запущен D-Bus демон. Или нужно какие-то переменные окружения выставлять.
Я смогу проверить работу демона на OS X только в выходные.

**Comment by Anonym-tsk** [comment]
Жду с нетерпением.
А нет ли способа получать данные с газоанализатора как-нибудь попроще, без dbus?

**Comment by dmage** [comment]
Нет, пока что это единственный вариант. До этого был просто вывод в stdout, но скрестить с GNOME оказалось такой вариант не так просто. D-Bus был выбран, т.к. в GNOME и KDE это стандартная шина данных. И случае с GNOME это получается очень удачный вариант: демон ставится пакетным менеджером, а отображалка значений пишется на JS из ставится из браузера.
Однако в случае OS X или какого-нибудь роутера, где нет D-Bus, согласен, этот вариант уже не кажется таким удачным. Если какие-то пожелания в каком виде получать данные? Есть еще идея сделать HTTP демон, но тогда вероятно он будет на Go :)

**Comment by Anonym-tsk** [comment]
Идеально было бы просто получить бинарник, который в stdout выводит всю информацию, по аналогии с sensors, например. Ну или два бинарника - для температуры и для co2. А уже над бинарником можно хоть dbus прикручивать, хоть gui, хоть что. Linux-way, мне кажется таким.

**Comment by Displacer** [comment]
Может просто UDP пакеты слать, возможно даже широковещательно?

**Comment by Anonym-tsk** [comment]
Я собрал бинарник без dbus - в убунте работает, а на маке libusb не завелся.
https://github.com/libusb/libusb/wiki/FAQ#How_can_I_run_libusb_applications_under_Mac_OS_X_if_there_is_already_a_kernel_extension_installed_for_the_device

**Comment by Displacer** [comment]
В принципе я бы мог бы сам попробовать сделать UDP версию для OpenWRT и потенциально работающую на MacOS, если еще этим никто не занялся.

**Comment by dmage** [comment]
Для обсуждения OpenWrt завел отдельную задачу: #8

**Comment by dmage** [comment]
Дополнительно вынес работу с устройством в отдельную библиотеку.

**Comment by dmage** [comment]
> Unable to connect to D-Bus: Не удалось подключиться к: No such file or directory

Это "решается" заменой SYSTEM шины на SESSION, т.к. D-Bus из brew по-умолчанию предоставляет только сессионную шину. Однако дальше я получаю другую ошибку:

> Unable to connect to D-Bus: Произошла ошибка при создании процесса командной строки «dbus-launch --autolaunch=7bc2635ad4cbf1a5b59c433354fb3c34 --binary-syntax --close-stderr»: Дочерний процесс завершился с кодом 1

Если запустить эту команду отдельно, то получается более понятная ошибка:

> dbus-launch --autolaunch=7bc2635ad4cbf1a5b59c433354fb3c34 --binary-syntax --close-stderr
> Autolaunch requested, but X11 support not compiled in.
> Cannot continue.

Но даже если это решить, то, действительно, есть проблема с libusb:

> Take note this may not be possible for drivers like USB HID since it may be used by other USB HID device.

Что, как я понимаю, означает, что этот код на OS X не заработает.

**Comment by Anonym-tsk** [comment]
Вроде для libusb можно собрать kext, но у меня не получилось подписать его. Есть ещё вариант не использовать libusb, но я в этом не силён.

**Comment by dmage** [comment]
Загрузил бранч hidapi в котором работа с датчиком реализована через hidapi.

**Comment by Anonym-tsk** [comment]
Спасибо. Проверить смогу только во вторник.

**Comment by dmage** [comment]
Проверил на OS X Yosemite, добавил co2mon-dumper (имплементация без D-Bus), заработало.
Однако мне не нравится дублирование кода между co2mon-dumper и co2mond.

**Comment by Anonym-tsk** [comment]
```
-- checking for module 'hidapi-libusb'
--   package 'hidapi-libusb' not found
```
Пытаюсь собрать бранч hidapi.

**Comment by dmage** [comment]
Добавил fallback на "hidapi", в brew называется hidapi.

**Comment by Anonym-tsk** [comment]
Работает!
До нужного мне состояния уже смогу допилить сам, спасибо.

**Comment by dmage** [comment]
В master версия, которая работает с hidapi.
