### ISSUE TITLE
Поддержка OpenWrt

### ISSUE THREAD

**Issue by dmage** [dmage/co2mon#8]

**Comment by dmage** [comment]
Разделил получение данных от устройства (эти занимается libco2mon) и доставку до пользователя через D-Bus (co2mond). libco2mon можно переиспользовать для OpenWrt.

**Comment by dmage** [comment]
Обнаружил, что там все-таки есть D-Bus: http://downloads.openwrt.org/attitude_adjustment/12.09-beta/ar71xx/generic/packages/dbus_1.4.14-2_ar71xx.ipk

**Comment by Displacer** [comment]
Вот здесь про dbus: http://wiki.openwrt.org/doc/techref/netifd
Вроде как dbus может и можно было бы использовать, но нерационально по ресурсам. По моему UDP вполне себе рабочий и неплохой вариант бы был, из минусов только разве что необходимость резервировать какой-то порт. Других минусов пока не вижу.

**Comment by dmage** [comment]
Если продолжать использовать подход подписки на новые значения, то нужно реализовывать методы subscribe/unsubcribe и отслеживание подписанных клиентов.
Broadcast в сеть (и это уже не только локальная IPC) мне кажется ужасным решением, т.к. получатель вероятно будет один, а спамиться будет вся сеть. Так же есть сети, в которых broadcast попросту запрещен. И, в конце концов, потребитель данных может находится в другом широковещательном сегменте.
Broadcast на 127.0.0.0/8, вероятно, рабочее решение.

Можно придумать еще более простой вариант: 2 файла с текущими значениями температуры и CO2. Демон, по мере получения новых данных, будет значения в файлах обновлять. В итоге простым cat'ом можно посмотреть текущие значения температуры и CO2.

**Comment by Anonym-tsk** [comment]
А почему бы не сделать бинарник, который отдает данные в stdout, а всю внешнюю обвязку сделать отдельно? @Displacer бы сделал UDP рассылку, я для себя сделал бы отдачу по HTTP (мне так удобнее данные читать), кто-то может еще бы что-нибудь придумал.

**Comment by dmage** [comment]
С моей точки зрения идеальным вариантом является пакет с командой co2mon-status, которая в stdout выводит текущие значения (в пакете может быть еще что-то, например какой-нибудь демон). Есть два способа реализации такой команды:

  1. читать данные из устройсва напрямую, но при этом возможны задержки до 5 секунд и нет возможности запустить параллельно 2-ю копию,
  2. читать данные из демона, который в фоне собирает данные.

И вот бинарник пишущий все данные из устройства в stdout это примерно 1-й путь. Такой была первая версия. Оказалось, что этот подход не очень удобен, если хочется данные слать в InfluxDB, в трей и иметь возможность посмотреть текущие значения в терминале и все было переписано на PubSub схему с D-Bus.

**Comment by Anonym-tsk** [comment]
Я предлагаю первый вариант - просто читать актуальные данные из устройства. Демона можно сделать отдельно. А можно и оба варианта, просто лично я предпочитаю запрашивать данные клиентским приложением, а не пушить их демоном.

**Comment by Displacer** [comment]
По udp рассылка может быть адресной и настраиваться в конфиге. По сути своей для OpenWRT пока вижу две разумные альтернативы: родной для OpenWRT ubus или всё-таки udp. Если же задуматься о MacOS и кросс-платформенной совместимости, то можно рассмотреть вообще экзотические варианты в духе CORBA.

**Comment by dmage** [comment]
В master версия, которая более не требует D-Bus, а работает через файлы.
