### ISSUE TITLE
magic_table & decode_buf

### ISSUE THREAD

**Issue by Lokis92** [dmage/co2mon#9]
Пытаюсь повторить процедуру на java (usb4java), но никак не удается получить правильные данные на выходе. Magic_table всегда разная (так должно быть?), result[4] тоже всегда разная (и не 0x0d), checksum (result[3]) тоже не сходится. 
Подскажите пожалуйста, где можно узнать подробности такого странного кодирования данных, включая magic_table, Htemp99e и пр. 
Где-то есть описание, либо был жесткий reverse engineering?
Спасибо.

**Comment by dmage** [comment]
Был жесткий reverse engineering. Вероятно забыта отправка таблицы или декодировка ответа:
https://github.com/dmage/co2mon/blob/master/libco2mon/src/co2mon.c#L191
https://github.com/dmage/co2mon/blob/master/libco2mon/src/co2mon.c#L217

**Comment by Lokis92** [comment]
Отправка? Мне показалось, что magic_table как раз получается из устройства: 
```
   co2mon_magic_table_t magic_table = {0};
   co2mon_send_magic_table(dev, magic_table)
```

Ошибся?
//если magic_table получена правильно, то декодировка должна работать, copy-paste, тут трудно ошибиться.

**Comment by dmage** [comment]
Она именно отправляется на устройства, а устройство с её помощью кодирует данные. Оригинальный код её строил на основе текущего времени и еще чего-то. Я просто нули оставил, оно и так работает.

**Comment by Lokis92** [comment]
Спасибо, все заработало. 
А есть какие-нибудь идеи, что могут означать другие коды: 
0x41 (всегда 0), 0x43, 0x4f, 0x52, и т.д.?

**Comment by dmage** [comment]
Нет, здесь тоже гадают по поводу этих значений: https://revspace.nl/CO2MeterHacking
